/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import alaposztalyok.Diak;
import alaposztalyok.Tantargy;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modellcsomag.RendezhetoListModel;
import vezerles.Vezerlo;


/**
 *
 * @author :)
 */
public class DiakPanel extends javax.swing.JPanel{

    private RendezhetoListModel<Diak> diakModel = 
            new RendezhetoListModel<Diak>();
    private DefaultComboBoxModel<Tantargy> tantargyBoxModel = 
            new DefaultComboBoxModel<>();
    private Vezerlo vezerlo;
    
    public DiakPanel() {
        initComponents();   
        lstDiakok.setModel(diakModel);
        cmbTantargyak.setModel(tantargyBoxModel);
    }

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDiakok = new javax.swing.JList<>();
        lblVizsgazo = new javax.swing.JLabel();
        lblTargy = new javax.swing.JLabel();
        lblJegy = new javax.swing.JLabel();
        cmbTantargyak = new javax.swing.JComboBox<>();
        txtJegy = new javax.swing.JTextField();
        btnVizsga = new javax.swing.JButton();

        setBackground(new java.awt.Color(251, 241, 201));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("A diákok:");

        lstDiakok.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstDiakok);

        lblTargy.setText("Tárgy:");

        lblJegy.setText("Osztályzat: ");

        cmbTantargyak.setPreferredSize(new java.awt.Dimension(130, 23));

        btnVizsga.setText("Vizsga");
        btnVizsga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVizsgaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTargy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJegy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtJegy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVizsga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cmbTantargyak, 0, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblVizsgazo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVizsgazo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTargy)
                    .addComponent(cmbTantargyak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJegy)
                    .addComponent(txtJegy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVizsga))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVizsgaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizsgaActionPerformed
        try {
            Diak diak = lstDiakok.getSelectedValue();
            Tantargy tantargy = (Tantargy) cmbTantargyak.getSelectedItem();
            if (diak == null || tantargy == null) {
                throw new NullPointerException();
            }
            int jegy = Integer.parseInt(txtJegy.getText());
            vezerlo.vizsgaztatas(diak, tantargy, jegy);
            
        } catch (NullPointerException e1) {
            e1.printStackTrace();
            JOptionPane.showMessageDialog(jScrollPane1, "Hibás választás");
        } catch (NumberFormatException e2){
            JOptionPane.showMessageDialog(jScrollPane1, "Hibás jegy");
        }
    }//GEN-LAST:event_btnVizsgaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVizsga;
    private javax.swing.JComboBox<Tantargy> cmbTantargyak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJegy;
    private javax.swing.JLabel lblTargy;
    private javax.swing.JLabel lblVizsgazo;
    private javax.swing.JList<Diak> lstDiakok;
    private javax.swing.JTextField txtJegy;
    // End of variables declaration//GEN-END:variables

    public void kiir(List<Diak> diakok, List<Tantargy> tantargyak) {

        Collections.sort(tantargyak);
        for (Tantargy tantargy : tantargyak) {
            tantargyBoxModel.addElement(tantargy);
        }
        
        for (Diak diak : diakok) {
            diakModel.addElement(diak);
        }
    }

    public void kiirDiakEredmeny(Diak diak, Tantargy tantargy, int jegy) {
        lblVizsgazo.setText(String.format("%s, %s, %s, %d", 
                diak.getNev(), diak.getKod(), 
                tantargy.getNev(), jegy));
        
        diakModel.removeElement(diak);
        diakModel.addElement(diak, true);
    }
}
