/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import grafikonhoz.Oszlop;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;
import vezerles.Vezerlo.OszlopTipus;

/**
 *
 * @author :)
 */
public class KimutatasPanel extends javax.swing.JPanel {
    
    private List<Oszlop> diakOszlopok = new ArrayList<>();
    private List<Oszlop> koltsegteritesesOszlopok = new ArrayList<>();

    private Color diakSzin;
    private Color ktgDiakSzin;
    private int oszlopNoveloLepeskoz;
    
    public KimutatasPanel() {
        initComponents();   
        lblDiak.setBackground(Color.blue);
        lblKoltseges.setBackground(Color.red);        
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); 
        rajzolas(g);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDiak = new javax.swing.JLabel();
        lblKoltseges = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("     elégtelen        elégséges        közepes                jó                  jeles");

        jLabel2.setText("finanszírozott");

        lblDiak.setBackground(new java.awt.Color(0, 0, 255));
        lblDiak.setOpaque(true);

        lblKoltseges.setBackground(new java.awt.Color(204, 0, 0));
        lblKoltseges.setOpaque(true);

        jLabel3.setText("költségtérítéses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblKoltseges, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDiak, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblKoltseges, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDiak;
    private javax.swing.JLabel lblKoltseges;
    // End of variables declaration//GEN-END:variables

    public void oszlopGeneralas(){
        int[] xDiak = {22, 97, 172, 247, 322};
        int[] xKtgDiak = {57, 132, 207, 282, 357};
        for (int x : xDiak) {
            diakOszlopok.add(new Oszlop(x, Oszlop.getAlap(), diakSzin));
        }
        
        for (int x : xKtgDiak) {
            koltsegteritesesOszlopok.add(new Oszlop(x, Oszlop.getAlap(), ktgDiakSzin));
        }   
    }

    public void oszlopModositas(OszlopTipus tipus, int jegy) {
        Oszlop oszlop;
        if(tipus == OszlopTipus.KOLTSEGTERITESES){
            oszlop = koltsegteritesesOszlopok.get(jegy-1);
        }else{
            oszlop = diakOszlopok.get(jegy-1);
        }
        oszlop.setFelsoY(oszlop.getFelsoY() - oszlopNoveloLepeskoz);
        
        repaint();
    }

    public void setDiakSzin(Color diakSzin) {
        this.diakSzin = diakSzin;
    }

    public void setKtgDiakSzin(Color ktgDiakSzin) {
        this.ktgDiakSzin = ktgDiakSzin;
    }

    public void setOszlopNoveloLepeskoz(int oszlopNoveloLepeskoz) {
        this.oszlopNoveloLepeskoz = oszlopNoveloLepeskoz;
    }

  
    public void rajzolas(Graphics g) {
        for (Oszlop oszlop : diakOszlopok) {
            oszlop.rajzol(g);
        }
        for (Oszlop oszlop : koltsegteritesesOszlopok) {
            oszlop.rajzol(g);
        }       
    }



}
